# Generated by Django 5.0 on 2023-12-18 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhasrole',
            name='name',
        ),
        migrations.AddField(
            model_name='userhasrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.role'),
        ),
    ]
