# Generated by Django 5.0 on 2023-12-12 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProduitFini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.role')),
            ],
        ),
        migrations.CreateModel(
            name='EntreeFourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('fourniture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.fourniture')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeFourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('etat', models.BooleanField(default=False)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.fournisseur')),
                ('fourniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.fourniture')),
            ],
        ),
        migrations.CreateModel(
            name='EntreeMp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('matiere_premiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.matierepremiere')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeMp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('etat', models.BooleanField(default=False)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.fournisseur')),
                ('matiere_premiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.matierepremiere')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('agent_pai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_pai', to='bakery.agent')),
                ('agent_rec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.agent')),
            ],
        ),
        migrations.CreateModel(
            name='PfHasPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_updated', models.DateField(auto_now_add=True, null=True)),
                ('heure_updated', models.TimeField(auto_now_add=True, null=True)),
                ('produit_fini', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.produitfini')),
            ],
        ),
        migrations.CreateModel(
            name='EntreePF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('produit_fini', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.produitfini')),
            ],
        ),
        migrations.CreateModel(
            name='SortieFourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('fourniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.fourniture')),
            ],
        ),
        migrations.CreateModel(
            name='SortieMp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('matiere_premiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.matierepremiere')),
            ],
        ),
        migrations.CreateModel(
            name='SortiePF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit_fini', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.produitfini')),
            ],
        ),
        migrations.CreateModel(
            name='StockFourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('fourniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.fourniture')),
            ],
        ),
        migrations.CreateModel(
            name='StockMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('matiere_premiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.matierepremiere')),
            ],
        ),
        migrations.CreateModel(
            name='StockPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.produitfini')),
            ],
        ),
        migrations.AddField(
            model_name='produitfini',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.unite'),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.unite'),
        ),
        migrations.AddField(
            model_name='fourniture',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.unite'),
        ),
    ]
