# Generated by Django 5.0 on 2023-12-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreemp',
            name='date_exp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
