# Generated by Django 5.0 on 2023-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_stockfourniture_entree_stockfourniture_sortie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='entreefourniture',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entreemp',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entreemp',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default=('FC', 'FC'), max_length=25),
        ),
        migrations.AddField(
            model_name='entreepf',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiement',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default=('FC', 'FC'), max_length=25),
        ),
        migrations.AddField(
            model_name='pfhasprice',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default=('FC', 'FC'), max_length=25),
        ),
        migrations.AddField(
            model_name='sortiefourniture',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sortiemp',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sortiepf',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sortiepf',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default=('FC', 'FC'), max_length=25),
        ),
    ]
