# Generated by Django 5.0 on 2023-12-18 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
        ('bakery', '0005_remove_stockmp_entree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
