# Generated by Django 5.0 on 2023-12-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_agent_initial_alter_agent_email_alter_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommandefourniture',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default=('FC', 'FC'), max_length=25),
        ),
        migrations.AddField(
            model_name='lignecommandemp',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default=('FC', 'FC'), max_length=25),
        ),
    ]
