# Generated by Django 5.0 on 2023-12-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0008_lignecommandefourniture_devise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='fcc17bda5d', max_length=10),
        ),
        migrations.AddField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='2af80a623e', max_length=10),
        ),
    ]
