# Generated by Django 5.0 on 2023-12-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0009_commandefourniture_ref_commandemp_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='b30e7a7f2d', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='7431478293', max_length=10),
        ),
        migrations.AlterField(
            model_name='lignecommandefourniture',
            name='qts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lignecommandemp',
            name='qts',
            field=models.IntegerField(default=0),
        ),
    ]
