# Generated by Django 5.0 on 2023-12-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0010_alter_commandefourniture_ref_alter_commandemp_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandefourniture',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default=('FC', 'FC'), max_length=25),
        ),
        migrations.AddField(
            model_name='commandemp',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default=('FC', 'FC'), max_length=25),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='9af882ec21', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='fb0424e3ab', max_length=10),
        ),
    ]
