# Generated by Django 5.0 on 2023-12-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0011_commandefourniture_devise_commandemp_devise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='devise',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('FC', 'FC')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='185742cc3f', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='devise',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('FC', 'FC')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='0e9232dc7d', max_length=10),
        ),
    ]
