# Generated by Django 5.0 on 2023-12-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0012_alter_commandefourniture_devise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='6880787b6a', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='25a48b210d', max_length=10),
        ),
    ]
