# Generated by Django 5.0 on 2023-12-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0013_alter_commandefourniture_ref_alter_commandemp_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='devise',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='8577ef50ab', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='devise',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='0a4d81d4c2', max_length=10),
        ),
    ]
