# Generated by Django 5.0 on 2023-12-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0015_alter_commandefourniture_ref_alter_commandemp_ref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandemp',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='0023dbfbce', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='7cc6ab937a', max_length=10),
        ),
        migrations.AlterField(
            model_name='sortiepf',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
