# Generated by Django 5.0 on 2023-12-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0016_alter_commandemp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='9a6c5e5dfc', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='12a2085887', max_length=10),
        ),
        migrations.AlterField(
            model_name='lignecommandefourniture',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
