# Generated by Django 5.0 on 2023-12-21 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0018_entreefourniture_devise_entreefourniture_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.fournisseur'),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='2773ad7cbb', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='cbd4d0e8ad', max_length=10),
        ),
    ]
