# Generated by Django 5.0 on 2023-12-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0019_alter_commandefourniture_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourniture',
            name='critic_qts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='critic_qts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produitfini',
            name='critic_qts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='956f2e7065', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='e751e165d9', max_length=10),
        ),
    ]
