# Generated by Django 5.0 on 2023-12-30 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0024_produitfini_price_alter_commandefourniture_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiffreAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default=('FC', 'FC'), max_length=25)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='1d53583d00', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='83a179e4a1', max_length=10),
        ),
        migrations.CreateModel(
            name='InvenduPf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default=('FC', 'FC'), max_length=25)),
                ('produit_fini', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.produitfini')),
            ],
        ),
    ]
