# Generated by Django 5.0 on 2023-12-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0025_chiffreaffaire_alter_commandefourniture_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandefourniture',
            name='delivered_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandemp',
            name='delivered_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='3c08a63b5c', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='f037381f95', max_length=10),
        ),
    ]
