# Generated by Django 5.0 on 2024-01-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0027_fourniture_total_entry_fourniture_total_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='d95bdd9195', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='f3935941fd', max_length=10),
        ),
        migrations.AlterField(
            model_name='invendupf',
            name='qts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
