# Generated by Django 5.0 on 2024-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0029_produitfini_total_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreemp',
            name='is_read_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='ed5c40af77', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='8857e2263e', max_length=10),
        ),
    ]
