# Generated by Django 5.0 on 2024-01-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0032_entreefourniture_taux_entreemp_taux_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent'},
        ),
        migrations.AlterModelOptions(
            name='commandefourniture',
            options={'verbose_name': 'Commande de fourniture'},
        ),
        migrations.AlterModelOptions(
            name='commandemp',
            options={'verbose_name': 'Commande de matière première'},
        ),
        migrations.AlterModelOptions(
            name='entreefourniture',
            options={'verbose_name': 'Entrées de fourniture'},
        ),
        migrations.AlterModelOptions(
            name='entreemp',
            options={'verbose_name': 'Entrées de matière première'},
        ),
        migrations.AlterModelOptions(
            name='entreepf',
            options={'verbose_name': 'Entrées de produit fini'},
        ),
        migrations.AlterModelOptions(
            name='invendupf',
            options={'verbose_name': 'Invendus de produit fini'},
        ),
        migrations.AlterModelOptions(
            name='matierepremiere',
            options={'verbose_name': 'Matière première'},
        ),
        migrations.AlterModelOptions(
            name='produitfini',
            options={'verbose_name': 'Produit fini'},
        ),
        migrations.AlterModelOptions(
            name='sortiefourniture',
            options={'verbose_name': 'Sortie de fourniture'},
        ),
        migrations.AlterModelOptions(
            name='sortiemp',
            options={'verbose_name': 'Sortie de matière première'},
        ),
        migrations.AlterModelOptions(
            name='sortiepf',
            options={'verbose_name': 'Sortie de produit fini'},
        ),
        migrations.AlterModelOptions(
            name='taux',
            options={'verbose_name': 'Taux de change'},
        ),
        migrations.AlterModelOptions(
            name='unite',
            options={'verbose_name': 'Unité de mésure'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='fc0accb103', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date de commande'),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='delivered_at',
            field=models.DateField(blank=True, null=True, verbose_name='date de livraison'),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='893c046707', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='address',
            field=models.TextField(verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='produitfini',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='prix'),
        ),
    ]
