# Generated by Django 5.0 on 2024-01-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0033_alter_agent_options_alter_commandefourniture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiffreaffaire',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date de commande'),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='delivered_at',
            field=models.DateField(blank=True, null=True, verbose_name='date de livraison'),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='9fd1af42d2', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='452355fedd', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='entreefourniture',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25),
        ),
        migrations.AlterField(
            model_name='entreefourniture',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='cout total'),
        ),
        migrations.AlterField(
            model_name='entreemp',
            name='date_exp',
            field=models.DateField(blank=True, null=True, verbose_name='date expiration'),
        ),
        migrations.AlterField(
            model_name='entreemp',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25),
        ),
        migrations.AlterField(
            model_name='entreemp',
            name='matiere_premiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.matierepremiere', verbose_name='matière première'),
        ),
        migrations.AlterField(
            model_name='entreemp',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='cout total'),
        ),
        migrations.AlterField(
            model_name='entreepf',
            name='produit_fini',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.produitfini', verbose_name='produit fini'),
        ),
        migrations.AlterField(
            model_name='invendupf',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25),
        ),
        migrations.AlterField(
            model_name='invendupf',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cout total'),
        ),
        migrations.AlterField(
            model_name='invendupf',
            name='produit_fini',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.produitfini', verbose_name='Produit fini'),
        ),
        migrations.AlterField(
            model_name='lignecommandefourniture',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25),
        ),
        migrations.AlterField(
            model_name='lignecommandemp',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25),
        ),
        migrations.AlterField(
            model_name='pfhasprice',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25),
        ),
        migrations.AlterField(
            model_name='sortiepf',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25),
        ),
        migrations.AlterField(
            model_name='sortiepf',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix'),
        ),
    ]
