# Generated by Django 5.0 on 2024-01-09 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0036_alter_commandefourniture_ref_alter_commandemp_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='6dbcce0a4f', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='441658d9d0', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='invendupf',
            name='heure',
            field=models.TimeField(default=datetime.time(11, 17, 35, 501255), null=True),
        ),
    ]
