# Generated by Django 5.0 on 2024-01-09 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0039_alter_commandefourniture_ref_alter_commandemp_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='60f3d26a08', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='c650525343', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='invendupf',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 11, 29, 32, 279451), null=True),
        ),
        migrations.AlterField(
            model_name='invendupf',
            name='heure',
            field=models.TimeField(default=datetime.datetime(2024, 1, 9, 11, 29, 32, 279465), null=True),
        ),
    ]
