# Generated by Django 5.0 on 2024-01-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0040_alter_commandefourniture_ref_alter_commandemp_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='c30426ed18', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='5440c26553', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='invendupf',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invendupf',
            name='heure',
            field=models.TimeField(null=True),
        ),
    ]
