# Generated by Django 5.0 on 2024-01-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0041_alter_commandefourniture_ref_alter_commandemp_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitfini',
            name='type_produit',
            field=models.CharField(blank=True, choices=[('BOULANGERIE', 'BOULANGERIE'), ('RESTAURANT', 'RESTAURANT'), ('BOULANGERIE ET RESTAURANT', 'BOULANGERIE ET RESTAURANT')], max_length=100, null=True, verbose_name='type de produit'),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='5cc779a21b', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='bdb03c988b', max_length=10, verbose_name='réference'),
        ),
    ]
