# Generated by Django 5.0 on 2024-01-18 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0042_produitfini_type_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandePf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='79c5bd3533', max_length=10, verbose_name='réference')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='date de commande')),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('etat', models.BooleanField(default=False)),
                ('devise', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Commande de produit finis',
            },
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='6acb94c33f', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='302fde4cf1', max_length=10, verbose_name='réference'),
        ),
        migrations.CreateModel(
            name='EntreePfPt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('produit_fini', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.produitfini', verbose_name='produit fini')),
            ],
            options={
                'verbose_name': 'Entrées de produit fini du petit stock',
            },
        ),
        migrations.CreateModel(
            name='LigneCommandePf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25)),
                ('taux', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.commandepf')),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.produitfini')),
            ],
        ),
        migrations.CreateModel(
            name='SortiePfPt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25)),
                ('completed', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('produit_fini', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.produitfini')),
            ],
            options={
                'verbose_name': 'Sortie de produit fini du petit stock',
            },
        ),
    ]
