# Generated by Django 5.0 on 2024-01-20 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0043_commandepf_alter_commandefourniture_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='21f4154abb', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='519be810bb', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='commandepf',
            name='ref',
            field=models.CharField(default='54fd550943', max_length=10, verbose_name='réference'),
        ),
        migrations.CreateModel(
            name='EntreeMpPt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('date_exp', models.DateField(blank=True, null=True, verbose_name='date expiration')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='cout total')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], default='FC', max_length=25)),
                ('completed', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_read_expired', models.BooleanField(default=False)),
                ('taux', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('matiere_premiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.matierepremiere', verbose_name='matière première')),
            ],
            options={
                'verbose_name': 'Entrées de matière première',
            },
        ),
        migrations.CreateModel(
            name='SortieMpPt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('heure', models.TimeField(auto_now_add=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('matiere_premiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.matierepremiere')),
            ],
            options={
                'verbose_name': 'Sortie de matière première du petit stock',
            },
        ),
    ]
