# Generated by Django 5.0 on 2024-01-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0045_matierepremiere_type_mp_alter_commandefourniture_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreemppt',
            name='price',
        ),
        migrations.RemoveField(
            model_name='entreemppt',
            name='taux',
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='53f01fa53b', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='2bccdfc5a3', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='commandepf',
            name='ref',
            field=models.CharField(default='e90fed412e', max_length=10, verbose_name='réference'),
        ),
    ]
