# Generated by Django 5.0 on 2024-01-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0046_remove_entreemppt_price_remove_entreemppt_taux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreemppt',
            name='devise',
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='63fdcbe308', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='ce15418c9e', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='commandepf',
            name='ref',
            field=models.CharField(default='9f5db15064', max_length=10, verbose_name='réference'),
        ),
    ]
