# Generated by Django 5.0 on 2024-01-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0047_remove_entreemppt_devise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandepf',
            options={'verbose_name': 'Ventes de produit finis'},
        ),
        migrations.AddField(
            model_name='commandepf',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commandepf',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='1596f9455d', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='bb3037385c', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='commandepf',
            name='ref',
            field=models.CharField(default='d1387ffb1b', max_length=10, verbose_name='réference'),
        ),
    ]
