# Generated by Django 5.0 on 2024-01-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0049_entreprise_foodpack_alter_commandepf_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortiepack',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='sortiepack',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='invendupack',
            name='pack',
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='d7fe8d5200', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='d0efd2d6ec', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='commandepf',
            name='ref',
            field=models.CharField(default='d2351b5001', max_length=10, verbose_name='réference'),
        ),
        migrations.DeleteModel(
            name='EntreePack',
        ),
        migrations.DeleteModel(
            name='Entreprise',
        ),
        migrations.DeleteModel(
            name='SortiePack',
        ),
        migrations.DeleteModel(
            name='FoodPack',
        ),
        migrations.DeleteModel(
            name='InvenduPack',
        ),
    ]
