# Generated by Django 5.0 on 2024-02-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0051_commandepf_table_number_alter_commandefourniture_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandepf',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='70b0d5b6e9', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='3dcfeff776', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='commandepf',
            name='ref',
            field=models.CharField(default='ec564f6741', max_length=10, verbose_name='réference'),
        ),
    ]
