# Generated by Django 5.0 on 2024-02-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0052_commandepf_date_time_alter_commandefourniture_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandepf',
            name='cloture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='973853d072', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='cfd8ad74c3', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='commandepf',
            name='ref',
            field=models.CharField(default='35172d2c04', max_length=10, verbose_name='réference'),
        ),
    ]
