# Generated by Django 5.0 on 2024-02-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0053_commandepf_cloture_alter_commandefourniture_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='dd5c026103', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='c0371cbe19', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='commandepf',
            name='ref',
            field=models.CharField(default='ed56f6d96f', max_length=10, verbose_name='réference'),
        ),
    ]
