# Generated by Django 5.0 on 2024-02-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0054_alter_commandefourniture_ref_alter_commandemp_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='3e8939870a', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='786ef5a1fb', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='commandepf',
            name='ref',
            field=models.CharField(default='792bb973b7', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='matierepremiere',
            name='type_mp',
            field=models.CharField(blank=True, choices=[('BOULANGERIE', 'BOULANGERIE'), ('RESTAURANT', 'RESTAURANT'), ('PACK', 'PACK'), ('BOULANGERIE ET RESTAURANT', 'BOULANGERIE ET RESTAURANT'), ('BOULANGERIE ET PACK', 'BOULANGERIE ET PACK')], max_length=100, null=True, verbose_name='type de matière'),
        ),
        migrations.AlterField(
            model_name='produitfini',
            name='type_produit',
            field=models.CharField(blank=True, choices=[('BOULANGERIE', 'BOULANGERIE'), ('RESTAURANT', 'RESTAURANT'), ('PACK', 'PACK'), ('BOULANGERIE ET RESTAURANT', 'BOULANGERIE ET RESTAURANT'), ('BOULANGERIE ET PACK', 'BOULANGERIE ET PACK')], max_length=100, null=True, verbose_name='type de produit'),
        ),
    ]
