# Generated by Django 5.0 on 2024-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0056_sortiemp_destination_sortiepf_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandepf',
            name='temp_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commandefourniture',
            name='ref',
            field=models.CharField(default='be328b4140', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemp',
            name='ref',
            field=models.CharField(default='e40a3de1e9', max_length=10, verbose_name='réference'),
        ),
        migrations.AlterField(
            model_name='commandepf',
            name='ref',
            field=models.CharField(default='be5c5d29c7', max_length=10, verbose_name='réference'),
        ),
    ]
